apiVersion: v1
kind: ConfigMap
metadata:
  name: ss-backend-configmap
data:
  redis-endpoint: redis-19006.c274.us-east-1-3.ec2.redns.redis-cloud.com
  redis-port: "19006"
  react-frontend-url: https://sharespace.client.com