apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-frontend-depl
  labels:
    app: ss-frontend-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ss-frontend
  template:
    metadata: 
      labels: 
        app: ss-frontend
    spec:
      containers:
      - name: ss-frontend-cont
        image: sfbimmortal/sharespace-frontend:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef: 
              name: ss-frontend-secret
              key: google-client-id
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ss-frontend-configmap
              key: node-backend-url